config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :users

  # there is a concept of a singular resource
  # which might make sense here.
  resources :sessions, :only => [:create, :new, :destroy]

  # Ehm...this is kinda confusing to me.  That `only` up above implies to me
  # that there's only one action, create, but here you are telling me that
  # there are acutally two more....is this an error or....which..huh?
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

  resources :posts do
    resources :comments
    # Something fishy about this......but we'll see more once we look at the
    # models.
    get '/comments/new(/:parent_id)', to: 'comments#new', as: :new_comment
    member do
      put 'upvote', to: 'posts#upvote'
      put 'downvote', to: 'posts#downvote'
    end
  end

  resources :comments do
    member do
      # Only put...hm....seems like you are creating a new one of these....it
      # would seem to me that the right verb is POST?
      put 'upvote', to: 'comments#upvote'
      put 'downvote', to: 'comments#downvote'
    end
  end

  # Why isn't this in with the posts resources?
  get 'tagged', to: 'posts#tagged'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  acts_as_votable
  acts_as_tree order: 'created_at DESC'
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  acts_as_taggable
  acts_as_votable
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  email_format = /\b[A-Z0-9._%-]+@(?:[A-Z0-9-]+\.)+[A-Z]{2,4}\b/i

  validates :user_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: email_format
  has_secure_password

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = current_user.comments
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    if session[:user_id]
      @comment = Comment.new(params[:comment])
    else
      redirect_to login_path
    end
  end

  def create
    # This method needs some love...
    #
    # Here are some options: can we move this logic into a model somewhere.
    # Like:
    #
    # Comment.create_for_post(some_parent)
    #
    params[:comment][:user_id] = session[:user_id] #changing the inputs is a smell to me...
    post = Post.find(params[:post_id])
    params[:comment][:post_id] = post.id
    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
    else
      @comment = Comment.new(comment_params)
    end

    if @comment.save
      redirect_to post
    else
      render 'new'
    end
  end

  def edit
    if session[:user_id]
      @comment = Comment.find(params[:id])
    else
      redirect_to login_path
    end
  end

  def update
    comment = Comment.find(params[:id])
    if comment.update(comment_params)
      redirect_to Post.find(comment.post_id)
    else
      render 'edit'
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_path(comment.post)
  end

  def upvote
    if session[:user_id]
      @comment = Comment.find(params[:id])
      @comment.upvote_by current_user
      redirect_to post_path(@comment.post)
    else
      redirect_to login_path
    end
  end

  def downvote
    if session[:user_id]
      @comment = Comment.find(params[:id])
      @comment.downvote_by current_user
      redirect_to post_path(@comment.post)
    else
      redirect_to login_path
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.hash_tree(limit_depth: 5)
  end

  def new
    if session[:user_id]
      @post = Post.new
    else
      redirect_to login_path
    end
  end

  def create
    user = User.find(session[:user_id])
    @post = user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    if session[:user_id]
      @post = Post.find(params[:id])
    else
      redirect_to login_path
    end
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_path(post.id)
    else
      render 'edit'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def upvote
    # Sometimes you can write an implementation, but not express the meaning.
    # I would much prefer to see `if current_user`.  Reason being thinking
    # about sessions and keys makes my brain hurt and I don't understand what
    # you _intention_ is.  Sometimes you take pieces of implementation and wrap
    # them in an English-friendly name so that your collaborators can
    # understand your _intention_.
    if session[:user_id]
      @post = Post.find(params[:id])
      @post.upvote_by current_user
      redirect_to posts_path
    else
      redirect_to login_path
    end
  end

  def downvote
    if session[:user_id]
      @post = Post.find(params[:id])
      @post.downvote_by current_user
      redirect_to posts_path
    else
      redirect_to login_path
    end
  end

  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
      @tag = params[:tag]
      render 'index'
    else
      render text: 'no post with this tag'
    end
  end
  private

  def post_params
    params.require(:post).permit(:title, :content, :address, :user_id, :tag_list)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(user_name: params[:session][:user_name])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.authenticate(params[:user][:password]) && @user.save 
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_user_path
    end

  end

    private
  
    def user_params
      params.require(:user).permit(:user_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      return User.find(session[:user_id])
    else
      return nil
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  # ...runs away....
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<li>
  <strong class="dark-blue"><%= comment.user.user_name %></strong> <%= comment.content %>
  <div class="comment-actions">
    <%= comment.get_upvotes.size %>
    <%=  link_to upvote_comment_path(comment), method: :put, class: "vote-buttons dark-blue" do %>
      <i class="fa fa-thumbs-up"></i>
    <% end %>
    <%= comment.get_downvotes.size %>
    <%=  link_to downvote_comment_path(comment), method: :put, class: "vote-buttons dark-blue" do%>
      <i class="fa fa-thumbs-down"></i>
    <% end %>
    <%= link_to 'reply', "/posts/#{@post.id}/comments/new/#{comment.id}" %>
    <% if current_user == comment.user %>
     <%= link_to 'edit', "/posts/#{@post.id}/comments/#{comment.id}/edit", class: "edit_comment" %>
     <%= link_to 'delete', comment_path(comment), method: :delete, class: "delete_comment", data: { confirm: 'Are you sure you want to delete the comment?' } %>
    <% end %>
  </div>
</li>

app/views/comments/_form.html.erb
<div class="small-10 small-centered large-5 large-centered columns">
  <div class="form-container text-center">
    <%= form_for(:comment, url: post_comments_path) do |f| %>
      <%= f.label :say_something, class: "form-input-label" %>
      <%= f.text_area :content, class: "comment-input-area" %>
      <%= f.hidden_field :parent_id %>
      <%= f.submit 'Add Comment', class: "button radius expand form-button" %>
    <% end %>
    <%= link_to 'Return to previous page', post_path(params[:post_id]), class: "return-link off-white" %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="small-10 small-centered large-5 large-centered columns">
  <div class="form-container text-center">
    <%= form_for(@comment) do |f| %>
      <%= f.label :say_something, class: "form-input-label" %>
      <%= f.text_area :content, class: "comment-input-area" %>
      <%= f.hidden_field :parent_id %>
      <%= f.submit 'Edit Comment', class: "button radius expand form-button" %>
    <% end %>
    <%= link_to 'Return to previous page', post_path(params[:post_id]), class: "return-link off-white" %>
  </div>
</div>

app/views/comments/index.html.erb
<div class="post-body small-12 medium-8 medium-centered columns">
  <h2 class="medium-centered large-8 large-centered columns"><i class="fa fa-cutlery green"></i> YourComments</h2>
  <% @comments.each do |comment| %>
    <div class="post-container small-12 medium-12 medium-centered large-8 large-centered columns">
      <div class="row">
        <div class="small-8 medium-7 large-8 columns">
          <h3><i class="fa fa-comment green"></i> <a href="#" class="post-link"><%= comment.content %></a></h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/layouts/_nav.erb
<div class="navbar">
  <div class="small-12 medium-8 medium-centered columns">
    <div class="row">
      <div id ="nav-logo">
        <h2><%= link_to 'WHERE CAN I EAT @ DBC-NYC?', root_path, class: "off-white text-center" %></h2>
      </div>
    </div>
    <div class="small-12 medium-6 medium-centered columns">
      <div id="nav-controls">
        <% if current_user %>
          <%= link_to 'Suggest', new_post_path, class: "button small default radius nav-button" %>
          <%= link_to 'Logout', logout_path, class: "button alert small radius nav-button" %>
        <% else %>
          <%= link_to 'Login', login_path, class: "button small radius nav-button" %>
          <%= link_to 'Signup', new_user_path, class: "button small success radius nav-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signup.erb
<%=  form_for @user do |f|  %>
  <%= f.label :username, class: "form-input-label" %><br>
  <%= f.text_field :user_name, class: "form-input-area" %><br>
  <%= f.label :email, class: "form-input-label" %><br>
  <%= f.text_field :email, class: "form-input-area" %><br>
  <%= f.label :password, class: "form-input-label" %><br>
  <%= f.password_field :password, class: "form-input-area" %><br>
  <%= f.submit 'Signup', class: "button success radius expand form-button"  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hungry Coders</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Dosis:400,600,700' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'layouts/nav' %>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="small-10 small-centered large-5 large-centered columns">
  <div class="form-container text-center">
    <%= form_for @post do |f| %>
      <%= f.label :Restaurant, class: "form-input-label" %><br>
      <%= f.text_field :title, class: "form-input-area", :placeholder => @post.title %><br>
       <%= f.label :Description, class: "form-input-label" %><br>
      <%= f.text_area :content, class: "form-input-area", :placeholder => @post.content %><br>
      <%= f.label :Address, class: "form-input-label" %><br>
      <%= f.text_field :address, :placeholder => @post.address, class: "form-input-area" %><br>
      <%= f.label :tags, class: "form-input-label" %>
      <%= f.text_field :tag_list, :placeholder => @post.tags, class: "form-input-area" %>
      <%= f.submit 'Edit Post', class: "button radius expand form-button" %>
    <% end %>
    <%= link_to 'Return to suggestions', root_path, class: "return-link off-white" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="index-body small-12 medium-8 medium-centered columns">
  <% if @tag %>
    <h3 class="tag-header off-white text-center">Returning results for <%= @tag %></h3>
  <% end %>
  <% @posts.each do |post| %>
    <div class="post-container small-12 medium-12 medium-centered large-8 large-centered columns">
      <div class="row">
        <div class="small-8 medium-7 large-8 columns">
          <h3><i class="fa fa-cutlery green"></i> <a href="/posts/<%= post.id %>" class="post-link"><%= post.title %></a></h3>
        </div>
        <div class="small-4 medium-5 large-4 columns">
          <div class="vote-box">
            <h3 class="dark-green"><strong><%= post.get_upvotes.size %></strong>
            <%=  link_to upvote_post_path(post), method: :put, class: "vote-buttons" do %>
              <i class="fa fa-thumbs-up"></i>
            <% end %>
            <strong><%= post.get_downvotes.size %></strong>
            <%=  link_to downvote_post_path(post), method: :put, class: "vote-buttons" do %>
              <i class="fa fa-thumbs-down"></i>
            <% end %></h3>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if current_user %>
    <div onclick="location.href='/posts/new';" class="suggest-container small-12 medium-12 medium-centered large-8 large-centered columns">
      <h3 class="text-center"><%= link_to 'Suggest a place to eat!', new_post_path, class: "suggest-button" %></h3>
    </div>
  <% else %>
    <div onclick="location.href='/login';" class="suggest-container small-12 medium-12 medium-centered large-8 large-centered columns">
      <h3 class="text-center"><%= link_to 'Please login to suggest!', login_path, class: "suggest-button" %></h3>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="small-10 small-centered large-5 large-centered columns">
  <div class="form-container text-center">
    <%= form_for @post do |f| %>
      <%= f.label :Restaurant, class: "form-input-label" %><br>
      <%= f.text_field :title, class: "form-input-area" %><br>
       <%= f.label :Description, class: "form-input-label" %><br>
      <%= f.text_area :content, class: "form-input-area" %><br>
      <%= f.label :Address, class: "form-input-label" %><br>
      <%= f.text_field :address, placeholder: "Optional. It would help a lot though!", class: "form-input-area" %><br>
      <%= f.label :tags, class: "form-input-label" %>
      <%= f.text_field :tag_list,  placeholder: "Example: Italian, Chinese...", class: "form-input-area" %>
      <%= f.submit 'Post', class: "button radius expand form-button" %>
    <% end %>
    <%= link_to 'Return to suggestions', root_path, class: "return-link off-white" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-body small-12 medium-10 medium-centered large-8 large-centered columns">
  <h2>
    <i class="fa fa-cutlery green"></i> <%= @post.title %>
    <% if current_user == @post.user %>
      <%= link_to '- edit post', edit_post_path(@post) %>
    <% end %>
  </h2>
  <h5><a href="http://maps.google.com/?q=<%= @post.address %>"><%= @post.address %></a></h5>
  <p>Tags:
  <% @post.tags.each do |tag| %>
    <%= link_to tag.name, tagged_url(:tag => tag.name) %>
  <% end %></p>
  <p class="post-content"><%= @post.content %></p>

<%= link_to "add a comment", new_post_comment_path(@post) %>

  <% if @comments.size > 0 %>
    <div class="comments-box">
      <ul class="no-bullet">
        <%= comments_tree_for @comments %>
      </ul>
    </div>
  <% end %>
  <br><%= link_to "return to suggestions page", root_path %><br>
  <% if current_user == @post.user %>
    <br><%= link_to 'delete post', post_path(@post), method: :delete, class: "button alert radius small delete-button", data: { confirm: 'Are you sure you want to delete the post?' } %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="small-10 small-centered large-4 large-centered columns">
  <div class="form-container text-center">
    <%= render 'layouts/signup' %>
    <%= link_to 'Already a member? Login!', login_path, class: "return-link off-white" %>
  </div>
</div>